#关闭selinux
- name: setenforce 0
  shell: "setenforce 0"
  failed_when: false

- name: set selinux disabled
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=disabled'

- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no 

- name: stop postfix
  service:
    name: postfix
    state: stopped
    enabled: no 

#- name: stop NetworkManager
#  systemd: name=NetworkManager state=stopped enabled=no
