---
# etcd service
- name: create etcd systemd.service 
  template: src=templates/template_etcd.service.j2 dest=/usr/lib/systemd/system/etcd.service force=yes

- name: Reload systemd
  command: systemctl daemon-reload

- name: start etcd
  service:
    name: etcd
    state: started
    enabled: yes
  ignore_errors: true
